package com.training.license.sharing.entities.enums;

public enum Position {
    DEVELOPER,
    SENIOR_DEVELOPER,
    CREATIVE_LEAD,
    DISCIPLINE_LEAD,
    TESTER,
    SENIOR_TESTER,
    ANALYST,
    SENIOR_ANALYST,
    SALES_REPRESENTATIVE,
    MARKETING_SPECIALIST,
    MANAGER,
    UX_DESIGNER,
    SENIOR_VISUAL_DESIGNER,
    FINANCE_SPECIALIST,
    PEOPLE_SPECIALIST,
}
